name: Primeiro WorkFlow

# Aqui iremos concluir os eventos (Gatilhos) para execução da pipeline
on:
  # Um primeiro evento será quando disparar um push
  push: 
    branches:
      - main
      - master
      - develop
  
  # Um outro evento será quando disparar um pull_request
  pull_request:
    branches:
      - main
      - master
      - develop


      # agora iremos criar algumas tarefas,
      # e uma lista de passos em cada um deles

jobs:

    job1:

      name: Primeira tarefa
      runs-on: ubuntu-latest

      #vamos incluir alguns passos para o primeiro job

      steps:
        - name: Passo 1
          run: echo "Executando o primeiro passo da pipeline"

        - name: Passo 2
          run: echo "Executando o segundo passo"
          
        - name: Passo 3
          run: echo "Executando o terceiro passo"
          
          
          
    job2:
    
        name: Segunda Tarefa
        runs-on: ubuntu-latest
        steps:
        
        #vamos incluir mais alguns passos para o segundo job
        
           - name: Passo 4
             run: echo "Executando o quarto job"
             
           - name: Passo 5
             run: echo "Executando o quinto job"
             
           - name: Passo 6
             run: echo "Executando o sexto job"
 
   
        
        
